### ISSUE TITLE
Release 0.1.3 gem

### ISSUE THREAD

**Issue by nuclearsandwich** [mirah/pindah#28]
I had issues with the currently released gem but master works.

What say we cut a release?

**Comment by abscondment** [comment]
Sounds good. I'll try to get it out this week.

**Comment by abscondment** [comment]
I have two commits in my fork that I'd like to include, but I want to make sure they don't break things for you. I updated to let the r20 tools include libraries correctly.

@nuclearsandwich , could you try out master from https://github.com/abscondment/pindah and let me know if there's any issue? If not, I'll merge those in for 0.13.0

**Comment by nuclearsandwich** [comment]
Hah, I had an incoming PR with a similar but.lesser change.. I have another that tweaks the templates a bit. I'll push as soon as school wifi allows.

**Comment by nuclearsandwich** [comment]
Just submitted PR #29 which makes minor template changes.

Running `rake test` on both abscondment/pindah master and mirah/pindah master gives the following error:

```
NameError: cannot load Java class org.mirah.macros.Macro
         for_name at org/jruby/javasupport/JavaClass.java:1205
  get_proxy_class at org/jruby/javasupport/JavaUtilities.java:34
      java_import at /opt/github/rbenv/versions/jruby-1.6.7.2/lib/ruby/site_ruby/shared/builtin/javasupport/core_ext/object.rb:46
              AST at /opt/github/rbenv/versions/jruby-1.6.7.2/lib/ruby/gems/1.8/bundler/gems/mirah-32e165874505/lib/mirah/transform/ast_ext.rb:10
            Mirah at /opt/github/rbenv/versions/jruby-1.6.7.2/lib/ruby/gems/1.8/bundler/gems/mirah-32e165874505/lib/mirah/transform/ast_ext.rb:2
           (root) at /opt/github/rbenv/versions/jruby-1.6.7.2/lib/ruby/gems/1.8/bundler/gems/mirah-32e165874505/lib/mirah/transform/ast_ext.rb:1
          require at org/jruby/RubyKernel.java:1033
           (root) at /opt/github/rbenv/versions/jruby-1.6.7.2/lib/ruby/gems/1.8/bundler/gems/mirah-32e165874505/lib/mirah/transform/ast_ext.rb:21
          require at org/jruby/RubyKernel.java:1033
           (root) at /opt/github/rbenv/versions/jruby-1.6.7.2/lib/ruby/gems/1.8/bundler/gems/mirah-32e165874505/lib/mirah/transform.rb:21
          require at org/jruby/RubyKernel.java:1033
           (root) at /opt/github/rbenv/versions/jruby-1.6.7.2/lib/ruby/gems/1.8/bundler/gems/mirah-32e165874505/lib/mirah.rb:13
          require at org/jruby/RubyKernel.java:1033
           (root) at /Users/steven/code/pindah/lib/pindah.rb:5
          require at org/jruby/RubyKernel.java:1033
         __file__ at /opt/github/rbenv/versions/jruby-1.6.7.2/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:15
           select at org/jruby/RubyArray.java:2395
           (root) at /opt/github/rbenv/versions/jruby-1.6.7.2/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:4
```

However, I'm able to remove the manually specified `:target => 16` from my project spec. So the changes appear to work.

**Comment by abscondment** [comment]
Hmm, yeah. AFAICT, this is happening when `lib/pindah.rb` tries to require
mirah. Strange.

**Comment by baroquebobcat** [comment]
I think the problem might be the `Gemfile` dep on mirah from git. Mirah has additional build dependencies that don't get setup on gem install. It would be safer to either use the released version, or to use a path dependency.

Otoh, I could try making mirah attempt to build itself on gem install when it's installed from git.

**Comment by nuclearsandwich** [comment]
I vote for using a release. A lot less duplication of effort thay way.

**Comment by abscondment** [comment]
I agree. I pinned it on 0.0.12, but I now see super weird rake issues:

```
[all the tests run and pass]
...
org.jruby.exceptions.RaiseException: (SystemExit) exit
rake aborted!
Command failed with status (-1): [/Users/brendan/.rbenv/versions/jruby-1.6.7...]
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/file_utils.rb:53:in `create_shell_runner'
org/jruby/RubyProc.java:270:in `call'
org/jruby/RubyProc.java:220:in `call'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/file_utils.rb:45:in `sh'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/file_utils_ext.rb:43:in `sh'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/file_utils.rb:82:in `ruby'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/file_utils_ext.rb:43:in `ruby'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/testtask.rb:99:in `define'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/file_utils_ext.rb:60:in `verbose'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/testtask.rb:98:in `define'
org/jruby/RubyProc.java:270:in `call'
org/jruby/RubyProc.java:220:in `call'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `execute'
org/jruby/RubyArray.java:1615:in `each'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `invoke_with_call_chain'
/Users/brendan/.rbenv/versions/jruby-1.6.7/lib/ruby/1.8/monitor.rb:191:in `mon_synchronize'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `top_level'
org/jruby/RubyArray.java:1615:in `each'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `top_level'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `run'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/Users/brendan/code/pindah/vendor/bundle/gems/rake-0.9.2.2/bin/rake:33:in `(root)'
org/jruby/RubyKernel.java:1058:in `load'
/Users/brendan/code/pindah/vendor/bundle/bin/rake:19:in `(root)'
Tasks: TOP => test
```

I get this even if I comment out all of the tests. Not sure what that means.

**Comment by abscondment** [comment]
Ok, I'm looking at this again. Only 4 months late :)

I'm currently waiting to hear back on #33 and #37, but I'm confident that these issues are all related to combining certain versions of Mirah and JRuby. Once I nail those down, I plan to update the README with known good versions and release 0.13. Yay.

**Comment by AtomicPair** [comment]
Alright, guys 'n gals, now that I've agreed to help Phil and Brendan with the managerial duties, I'd like to close out some of these stale issues and cut this 0.1.3 release we have been talking about for more than a year now.

In an effort to provide some clarity and direction, I've taken some time to clean up the issue tracker by adding several new tags and milestones, and I've tagged all but one open issue with the appropriate metadata to help us prioritize the work.  In the spirit of reviving this project and just getting stuff done, I propose we get this next release out the door as leanly and quickly as possible.  If necessary, we can always add an incremental 0.1.4 release to the roadmap before shooting for the stars with the 1.0.0 release.

What say y'all?  :-)

**Comment by baroquebobcat** [comment]
That sounds great.
