### ISSUE TITLE
org.apache.tools.ant.BuildException: taskdef class com.android.ant.SetupTask cannot be found

### ISSUE THREAD

**Issue by apaleslimghost** [mirah/pindah#30]
```
rake aborted!
org.apache.tools.ant.BuildException: taskdef class com.android.ant.SetupTask cannot be found
 using the classloader AntClassLoader[/Users/matt/Library/Android SDK/tools/lib/anttasks.jar:/Users/matt/Library/Android SDK/tools/lib/common.jar:/Users/matt/Library/Android SDK/tools/lib/sdklib.jar:/Users/matt/Library/Android SDK/tools/lib/androidprefs.jar:/Users/matt/Library/Android SDK/tools/lib/mkidentity.jar:/Users/matt/Library/Android SDK/tools/lib/commons-compress-1.0.jar:/Users/matt/Library/Android SDK/tools/lib/httpclient-4.1.1.jar:/Users/matt/Library/Android SDK/tools/lib/httpcore-4.1.jar:/Users/matt/Library/Android SDK/tools/lib/httpmime-4.1.1.jar:/Users/matt/Library/Android SDK/tools/lib/commons-logging-1.1.1.jar:/Users/matt/Library/Android SDK/tools/lib/commons-codec-1.4.jar:/Users/matt/Library/Android SDK/tools/lib/manifmerger.jar]
org/apache/tools/ant/taskdefs/Definer.java:622:in `addDefinition'
org/apache/tools/ant/taskdefs/Definer.java:239:in `execute'
org/apache/tools/ant/UnknownElement.java:291:in `execute'
sun/reflect/NativeMethodAccessorImpl.java:-2:in `invoke0'
sun/reflect/NativeMethodAccessorImpl.java:39:in `invoke'
sun/reflect/DelegatingMethodAccessorImpl.java:25:in `invoke'
java/lang/reflect/Method.java:597:in `invoke'
org/apache/tools/ant/dispatch/DispatchUtils.java:106:in `execute'
org/apache/tools/ant/Task.java:348:in `perform'
org/apache/tools/ant/Target.java:390:in `execute'
org/apache/tools/ant/helper/ProjectHelper2.java:180:in `parse'
org/apache/tools/ant/ProjectHelper.java:82:in `configureProject'
/usr/local/Cellar/jruby/1.6.7.2/libexec/lib/ruby/gems/1.8/gems/pindah-0.1.2/lib/pindah.rb:93:in `ant_setup'
/usr/local/Cellar/jruby/1.6.7.2/libexec/lib/ruby/gems/1.8/gems/pindah-0.1.2/lib/pindah.rb:68:in `spec='
/Users/matt/Code/Mirah/test/Rakefile:4:in `(root)'
org/jruby/RubyKernel.java:1058:in `load'
/Users/matt/Code/Mirah/test/Rakefile:25:in `load_rakefile'
/usr/local/Cellar/jruby/1.6.7.2/libexec/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:501:in `raw_load_rakefile'
/usr/local/Cellar/jruby/1.6.7.2/libexec/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:82:in `load_rakefile'
/usr/local/Cellar/jruby/1.6.7.2/libexec/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/usr/local/Cellar/jruby/1.6.7.2/libexec/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:81:in `load_rakefile'
/usr/local/Cellar/jruby/1.6.7.2/libexec/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:65:in `run'
/usr/local/Cellar/jruby/1.6.7.2/libexec/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/usr/local/Cellar/jruby/1.6.7.2/libexec/lib/ruby/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/usr/local/Cellar/jruby/1.6.7.2/libexec/lib/ruby/gems/1.8/gems/rake-0.9.2.2/bin/rake:33:in `(root)'
org/jruby/RubyKernel.java:1058:in `load'
/usr/local/Cellar/jruby/1.6.7.2/libexec/bin/rake:23:in `(root)'
```

**Comment by thypon** [comment]
Same issue here

**Comment by apaleslimghost** [comment]
Install Pindah from Git:

```
git clone git://github.com/mirah/pindah.git
cd pindah
jruby -S gem build pindah.gemspec
jruby -S gem install pindah-0.1.3.dev.gem
```

and the issue magically goes away. Good luck!
